# ── Database ──────────────────────────────────────────────
spring.datasource.url=jdbc:postgresql://localhost:5432/star_db
spring.datasource.username=star_user
spring.datasource.password=star2026!

# ── JPA / Hibernate ───────────────────────────────────────
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ── Fix the two warnings ───────────────────────────────────
spring.jpa.open-in-view=false

# ── Server ────────────────────────────────────────────────
server.port=8080
spring.application.name=star-api
logging.level.org.springframework.security=DEBUG
# ── JWT ────────────────────────────────────────────────
jwt.secret=starAssurancesSecretKey2026VeryLongSecretKeyForSecurity
jwt.expiration=86400000

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB
app.upload.dir=uploads/offers